Require Elixir v1.15
We fail to compile on previous versions:

    $ docker run --rm -it -v $PWD/mix.exs:/finch/mix.exs -v $PWD/README.md:/finch/README.md -v $PWD/lib:/finch/lib --workdir /finch -e MIX_ENV=prod \
        elixir:1.14 bash -c 'mix deps.get && mix compile && echo ok'
    ...
    == Compilation error in file lib/finch/http2/request_stream.ex ==
    ** (CompileError) lib/finch/http2/request_stream.ex:53: cannot use ^window outside of match clauses
        (elixir 1.14.5) src/elixir_bitstring.erl:254: :elixir_bitstring.expand_spec_arg/4
        (elixir 1.14.5) src/elixir_bitstring.erl:190: :elixir_bitstring.expand_each_spec/6
        (elixir 1.14.5) src/elixir_bitstring.erl:160: :elixir_bitstring.expand_specs/7
        (elixir 1.14.5) src/elixir_bitstring.erl:38: :elixir_bitstring.expand/8
        (elixir 1.14.5) src/elixir_bitstring.erl:14: :elixir_bitstring.expand/5

    $ docker run --rm -it -v $PWD/mix.exs:/finch/mix.exs -v $PWD/README.md:/finch/README.md -v $PWD/lib:/finch/lib --workdir /finch -e MIX_ENV=prod \
        elixir:1.14 bash -c 'mix deps.get && mix compile && echo ok'
    ...
    ok

I think it's fine to just bump as 1.15 is pretty old anyway!